name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_tests:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 8
            experimental: false
          - version: 11
            experimental: true

    steps:
      # Setup Java & Python
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
          architecture: x64

      # ICAT Ansible clone and install dependencies
      - name: Checkout icat-ansible
        uses: actions/checkout@v2
        with:
          repository: icatproject-contrib/icat-ansible
          path: icat-ansible
      - name: Install Ansible
        run: pip install -r icat-ansible/requirements.txt

      # Prep for running the playbook
      - name: Create Hosts File
        run: echo -e "[icat-server-dev-hosts]\nlocalhost ansible_connection=local" > icat-ansible/hosts
      - name: Prepare vault pass
        run: echo -e "icattravispw" > icat-ansible/vault_pass.txt
      - name: Move vault to directory it'll get detected by Ansible
        run: mv icat-ansible/vault.yml icat-ansible/group_vars/all
      - name: Replace default payara user with Actions user
        run: |
          sed -i -e "s/^payara_user: \"glassfish\"/payara_user: \"runner\"/" icat-ansible/group_vars/all/vars.yml

      # Force hostname to localhost - bug fix for previous ICAT Ansible issues on Actions
      - name: Change hostname to localhost
        run: sudo hostname -b localhost

      # Create local instance of ICAT
      - name: Run ICAT Ansible Playbook
        run: |
          ansible-playbook icat-ansible/icat-server-dev-hosts.yml -i icat-ansible/hosts --vault-password-file icat-ansible/vault_pass.txt -vv

      - name: Checkout icat-server
        uses: actions/checkout@v2

      # Payara must be sourced otherwise the Maven build command fails
      - name: Run Build
        run: |
          grep payara ~/.bash_profile > payara_path_command
          source payara_path_command
          mvn install -DskipTests

      - name: After Failure
        if: ${{ failure() }}
        run: |
          cat /home/runner/logs/lucene.log
          cat /home/runner/logs/icat.log
          cat /home/runner/payara*/glassfish/domains/domain1/logs/server.log
